#!/usr/bin/env python3
"""Telegram bot skeleton — copy and modify for your project.

This is the default skeleton generated by the `telegram-bot-auto-builder`
skill when AI generation fails or is unavailable. It provides a minimal,
functional bot that you can customise.

Usage:
  1. Copy this file to your project
  2. Set BOT_TOKEN in .env or os.environ
  3. Replace the handlers with your bot's logic
  4. Run: python main.py
"""

import os
import logging
from typing import Final

from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# ==== CONFIGURATION ====
BOT_TOKEN: Final[str] = os.environ.get("BOT_TOKEN", "")

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

# ==== COMMAND HANDLERS ====
async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /start command."""
    user = update.effective_user
    logger.info("User %s started the bot.", user.first_name)
    await update.message.reply_text(
        f"👋 سلام {user.first_name}! من ربات 인사를 می‌دی.\n"
        f" دستور /help رو بزن تا گزینه‌ها رو ببین."
    )

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /help command."""
    await update.message.reply_text(
        "🛠 دستورات موجود:\n"
        "/start - ربات را شروع کن\n"
        "/help - این راهنما رو نشان بده\n"
        "✅ - یک پیغام echo بگیر (برای تست)"
    )

# ==== MESSAGE HANDLER ====
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle text messages (echo)."""
    text: str = update.message.text
    logger.info("Received message: %s from %s", text, update.effective_user.first_name)
    await update.message.reply_text(f"شما گفتید: {text}")

# ==== MAIN ENTRY POINT ====
def main() -> None:
    """Start the bot."""
    if not BOT_TOKEN:
        logger.error("BOT_TOKEN environment variable is not set!")
        print("❌ خطأ: BOT_TOKEN تنظیم نشده است. .env فایل بساز و توکن رو بگذار.")
        return

    # Create the Application
    application = Application.builder().token(BOT_TOKEN).build()

    # Add handlers
    application.add_handler(CommandHandler("start", start_command))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(
        MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message)
    )

    # Run the bot until the user presses Ctrl-C
    application.run_polling()


if __name__ == "__main__":
    main()